# Generated by Django 5.1.4 on 2025-01-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_date_remove_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=' ', upload_to='blog_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default='images/default_image.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
